name: CI/CD Deployment to GitHub Pages

on:
  push:
    branches: [ "main" ]  # Kör bara på main-grenen

permissions:
  contents: read
  pages: write
  id-token: write  # Detta är den kritiska behörigheten som saknades

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      # Steg 1: Checka ut koden
      - uses: actions/checkout@v3

      # Steg 2: Installera Python (om du behöver köra skript)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Steg 3: Installera beroenden
      - name: Install dependencies
        run: pip install pytest faker

      # Steg 4: Kör dina skript
      - name: Run csvtojson.py
        run: python csvtojson.py

      # Steg 5: Förbered dist-mappen
      - name: Prepare dist folder
        run: |
          mkdir -p dist
          cp index.html script.js profiles.json dist/
          mv dist/profiles.json dist/data.json

      # Steg 6: Deploya
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4