name: CI/CD Deployment to GitHub Pages

on:
  push:
    branches: [ "main" ]  # Kör bara på main-grenen

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pytest faker

      - name: Run csvtojson.py
        run: python csvtojson.py

      - name: Prepare dist folder
        run: |
          mkdir -p dist
          cp index.html script.js profiles.json dist/
          mv dist/profiles.json dist/data.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
